# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-01 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
    ]
