# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-11 16:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190310_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 11, 16, 3, 37, 899404, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
